TypeBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('typefaces/', views.typeface_index, name='typeface-index'),
  path('typefaces/<int:typeface_id>/', views.typeface_detail, name='typeface-detail'),
  path('typefaces/create/', views.TypefaceCreate.as_view(), name='typeface-create'),
  path('typefaces/<int:pk>/update/', views.TypefaceUpdate.as_view(), name='typeface-update'),
  path('typefaces/<int:pk>/delete/', views.TypefaceDelete.as_view(), name='typeface-delete'),
  path('typefaces/<int:typeface_id>/add-rating-note/', views.add_rating_note, name='add-rating-note'),
  path('notes/<int:note_id>/delete/', views.delete_note, name='delete-note'),
  path('pairings/create/', views.PairingCreate.as_view(), name='pairing-create'),
  path('pairings/<int:pk>/', views.PairingDetail.as_view(), name='pairing-detail'),
  path('pairings/', views.PairingList.as_view(), name='pairing-index'),
  path('pairings/<int:pk>/update/', views.PairingUpdate.as_view(), name='pairing-update'),
  path('pairings/<int:pk>/delete/', views.PairingDelete.as_view(), name='pairing-delete'),
  path('typefaces/<int:typeface_id>/assoc_pairing/<int:pairing_id>/', views.assoc_pairing, name='assoc-pairing'),
  path('typefaces/<int:typeface_id>/remove_pairing/<int:pairing_id>/', views.remove_pairing, name='remove-pairing'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Typeface(models.Model):
    CLASSIFICATION_CHOICES = [
        ('Serif', 'Serif'),
        ('Sans Serif', 'Sans Serif'),
        ('Slab Serif', 'Slab Serif'),
        ('Display', 'Display'),
        ('Script', 'Script'),
        ('Monospace', 'Monospace'),
        ('Handwritten', 'Handwritten'),
        ('Blackletter', 'Blackletter'),
    ]
        
    name = models.CharField(max_length=100)
    designer = models.CharField(max_length=100)
    classification = models.CharField(max_length=100, choices=CLASSIFICATION_CHOICES)
    image = models.ImageField(upload_to='typefaces/')
    link = models.URLField(max_length=200)
    pairings = models.ManyToManyField('Pairing')
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('typeface-detail', kwargs={'typeface_id': self.id})


class Rating(models.Model):
    RATING_CHOICES = [
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★'),
    ]

    rating = models.IntegerField(choices=RATING_CHOICES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    typeface = models.ForeignKey(Typeface, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'typeface') 

    def __str__(self):
        return f"{self.user.username} – {self.get_rating_display()}"


class Note(models.Model):
    note = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    typeface = models.ForeignKey(Typeface, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} – {self.note[:30]}"

    class Meta:
        ordering = ['-created_at']



class Pairing(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='pairings/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pairing-detail', kwargs={'pk': self.id})

main_app/forms.py
from django import forms
from .models import Rating, Note

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['rating']
        widgets = {
            'rating': forms.Select(attrs={
                'class': 'form-control'
            }),
        }

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['note']
        widgets = {
            'note': forms.Textarea(attrs={
                'placeholder': 'Write your ideas...',
                'rows': 3,
                'class': 'form-control'
            }),
        }

main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from .models import Typeface, Rating, Note
from .forms import RatingForm, NoteForm
from .models import Pairing
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin



def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def typeface_index(request):
    typefaces = Typeface.objects.filter(user=request.user)
    return render(request, 'typefaces/index.html', {'typefaces': typefaces})


def typeface_detail(request, typeface_id):
    typeface = Typeface.objects.get(id=typeface_id)
    note_form = NoteForm()
    user_rating = None
    rating_form = RatingForm()

    pairings = Pairing.objects.exclude(id__in=typeface.pairings.all().values_list('id', flat=True))

    if request.user.is_authenticated:
        user_rating = typeface.rating_set.filter(user=request.user).first()
        if user_rating:
            rating_form = RatingForm(initial={'rating': user_rating.rating})

    return render(request, 'typefaces/detail.html', {
        'typeface': typeface,
        'rating_form': rating_form,
        'note_form': note_form,
        'user_rating': user_rating,
        'pairings': pairings,
    })

def add_rating_note(request, typeface_id):
    if request.method == 'POST':
        rating_value = request.POST.get('rating')
        note_text = request.POST.get('note')
        typeface = get_object_or_404(Typeface, id=typeface_id)

        if rating_value:
            Rating.objects.update_or_create(
                user=request.user,
                typeface=typeface,
                defaults={'rating': rating_value}
            )

        if note_text.strip():
            Note.objects.create(
                user=request.user,
                typeface=typeface,
                note=note_text
            )

        return redirect('typeface-detail', typeface_id=typeface_id)

def delete_note(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    if note.user == request.user:
        typeface_id = note.typeface.id
        note.delete()
        return redirect('typeface-detail', typeface_id=typeface_id)
    return redirect('typeface-detail', typeface_id=note.typeface.id)


def assoc_pairing(request, typeface_id, pairing_id):
    Typeface.objects.get(id=typeface_id).pairings.add(pairing_id)
    return redirect('typeface-detail', typeface_id=typeface_id)


def remove_pairing(request, typeface_id, pairing_id):
    typeface = Typeface.objects.get(id=typeface_id)
    typeface.pairings.remove(pairing_id)
    return redirect('typeface-detail', typeface_id=typeface.id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('cat-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)
    # Same as: 
    # return render(
    #     request, 
    #     'signup.html',
    #     {'form': form, 'error_message': error_message}
    # )



class TypefaceCreate(LoginRequiredMixin, CreateView):
    model = Typeface
    fields = ['name', 'designer', 'classification', 'image', 'link']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TypefaceUpdate(UpdateView):
    model = Typeface
    fields = ['name', 'designer', 'classification', 'image', 'link']

class TypefaceDelete(DeleteView):
    model = Typeface
    success_url = '/typefaces/'

class PairingCreate(CreateView):
    model = Pairing
    fields = '__all__'

class PairingList(ListView):
    model = Pairing

class PairingDetail(DetailView):
    model = Pairing

class PairingUpdate(UpdateView):
    model = Pairing
    fields = '__all__'

class PairingDelete(DeleteView):
    model = Pairing
    success_url = '/pairings/'

class Home(LoginView):
    template_name = 'home.html'

main_app/templates/typefaces/detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/typefaces/typeface-detail.css' %}" />
{% endblock %} 
{% block content %}

<section class="typeface-container">
<div class="typeface-top">
<div class="typeface-img">
<img src="{{ typeface.image.url }}" alt="{{ typeface.name }} preview" />
</div>

<div class="typeface-details">
<h1>{{ typeface.name }}</h1>
<h2>Designed by {{ typeface.designer }}</h2>
<p><strong>Classification:</strong> {{ typeface.classification }}</p>
<a href="{{ typeface.link }}" target="_blank" class="download-link">Download</a>


<div class="typeface-actions">
<a href="{% url 'typeface-update' typeface.id %}" class="btn warn">Edit</a>
<a href="{% url 'typeface-delete' typeface.id %}" class="btn danger">Delete</a>
</div>
</div>
</div>

<div class="bottom-section">

<div class="rates-container">
<h2>Ratings & Notes</h2>

<form action="{% url 'add-rating-note' typeface.id %}" method="post" autocomplete="off" class="Rating-form">
{% csrf_token %}
<div class="form-row">
<label for="id_rating">Rating:</label>
{{ rating_form.rating }}
</div>

<div class="form-row">
<label for="id_note">Note:</label>
{{ note_form.note }}
</div>

<button type="submit" class="btn submit">Submit</button>
</form>

<h3>All Notes</h3>
<table class="notes-table">
<thead>
<tr>
<th>Note</th>
<th>Date</th>
<th></th>
</tr>
</thead>
<tbody>

{% for note in typeface.note_set.all %}
<tr>
<td>{{ note.note }}</td>
<td>{{ note.created_at|date:"M d, Y" }}</td>
<td>
{% if user == note.user %}
<form method="POST" action="{% url 'delete-note' note.id %}">
{% csrf_token %}
<button type="submit" style="background: none; border: none; color: #fc4b03; cursor: pointer;">✕</button>
</form>
{% endif %}
</td>
</tr>
{% empty %}
<tr>
<td colspan="3">No notes yet.</td>
</tr>
{% endfor %}
</tbody>
</table>
      
</div>

<section class="pairings">
<h2>Pairings</h2>
<h3>{{ typeface.name }}’s Pairings</h3>
<div class="subsection-content">
{% if typeface.pairings.count %}
{% for pairing in typeface.pairings.all %}
<div class="pairing-container">
<a href="{% url 'pairing-detail' pairing.id %}">
<p>{{ pairing.name }}</p>
</a>
<form action="{% url 'remove-pairing' typeface.id pairing.id %}" method="post">
{% csrf_token %}
<button type="submit" class="btn danger" style="background: none; border: none; color: #fc4b03; cursor: pointer;">✕</button>
</form>
</div>
{% endfor %}
{% else %}
<p class="no-pairings">{{ typeface.name }} doesn’t have any pairings yet!</p>
{% endif %}
</div>


<h3>Available Pairings</h3>
<div class="subsection-content">
{% if pairings.count %}
{% for pairing in pairings %}
<div class="pairing-container">
<p>{{ pairing.name }}</p>
 <form action="{% url 'assoc-pairing' typeface.id pairing.id %}" method="post">
{% csrf_token %}
<button type="submit" class="btn submit">Pair it</button>
</form>
</div>
{% endfor %}
{% else %}
<p class="no-more">{{ typeface.name }} is already paired with all available pairings!</p>
{% endif %}
</div>
</section>

</div>

</section>
{% endblock %}

main_app/templates/typefaces/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/typefaces/typeface-index.css' %}" />
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>All Typefaces</h1>
</section>

<section class="card-container">
  {% for typeface in typefaces %}
  <div class="card">
    <div class="card-content">
      <a href="{% url 'typeface-detail' typeface.id %}">
        <div class="card-img-container">
          <img src="{{ typeface.image.url }}" alt="{{ typeface.name }} image" />
        </div>
      </a>
      <h2 class="card-title">{{ typeface.name }}</h2>
      <p><strong>Designer:</strong> {{ typeface.designer }}</p>
      <p><strong>Classification:</strong> {{ typeface.classification }}</p>
      <a href="{{ typeface.link }}" target="_blank" class="download-link">Download</a>
    </div>
  </div>
  
    </a>
    </div>
  {% endfor %}
</section>

{% endblock %}